version: '3'
services:
  agriconnect:
    build: .
    depends_on:
      - redis
      - mysql
      - mongo
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    env_file: .env.example
    command: ['npm', 'run', 'server']
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345 #
      MYSQL_DATABASE: agriconnect
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
  redis:
    image: redis
  mongo:
    image: mongo
